import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Home,Film,Bookmark,User,UserPlus,LogIn,Eye,EyeOff,ArrowRight,Menu,X}from'lucide-react';import'./styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
async function api(p,o={}){let r=await fetch(API+p,{...o,credentials:'include',headers:{'Content-Type':'application/json',...(o.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'Something went wrong');return d}
function App(){const[u,setU]=useState(undefined),[mode,setMode]=useState('login');useEffect(()=>api('/api/auth/me').then(x=>setU(x.user)).catch(()=>setU(null)),[]);if(u===undefined)return <div className="loading">Loading...</div>;if(!u)return <Auth mode={mode} setMode={setMode}/>;return <HomePage user={u} logout={async()=>{await api('/api/auth/logout',{method:'POST'});setU(null)}}/>}
function Auth({mode,setMode}){return <div className="auth"><div className="bg"/><div className="shade"/><main><div className="heading"><div><small>MOVIEHUB</small><h1>{mode==='login'?'Welcome Back':'Create Account'}</h1><p>{mode==='login'?'Login to continue your journey':'Join us and explore exclusive content'}</p></div><button className="switch" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?<UserPlus/>:<LogIn/>}<b>{mode==='login'?'SIGN UP':'SIGN IN'}</b></button></div>{mode==='login'?<Login/>:<Register/>}<div className="or">OR CONTINUE WITH</div><button className="google" onClick={()=>location.href=API+'/api/auth/google'}><strong>G</strong>{mode==='login'?'SIGN IN WITH GOOGLE':'Google Sign Up'}</button><div className="powered">© POWERED BY MOVIEHUB</div></main><Nav/></div>}
function Login(){const[e,setE]=useState(''),[p,setP]=useState(''),[show,setShow]=useState(false),[err,setErr]=useState('');async function go(x){x.preventDefault();try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:e,password:p})});location.reload()}catch(a){setErr(a.message)}}return <form onSubmit={go} className="form"><label><User/><input placeholder="Username or Email" type="email" required value={e} onChange={x=>setE(x.target.value)}/></label><label><span>🔒</span><input placeholder="Password" type={show?'text':'password'} required value={p} onChange={x=>setP(x.target.value)}/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></label><div className="remember"><input type="checkbox"/> Remember me</div>{err&&<div className="error">{err}</div>}<button className="submit">Login <ArrowRight/></button></form>}
function Register(){const[n,setN]=useState(''),[e,setE]=useState(''),[p,setP]=useState(''),[show,setShow]=useState(false),[err,setErr]=useState('');async function go(x){x.preventDefault();try{await api('/api/auth/register',{method:'POST',body:JSON.stringify({full_name:n,email:e,password:p})});location.reload()}catch(a){setErr(a.message)}}return <form onSubmit={go} className="form"><label><User/><input placeholder="Full Name" required value={n} onChange={x=>setN(x.target.value)}/></label><label><span>✉</span><input placeholder="Email Address" type="email" required value={e} onChange={x=>setE(x.target.value)}/></label><label><span>🔒</span><input placeholder="Password" type={show?'text':'password'} minLength="6" required value={p} onChange={x=>setP(x.target.value)}/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></label>{err&&<div className="error">{err}</div>}<button className="submit">Sign Up <ArrowRight/></button></form>}
function Nav(){return <nav><span className="active"><Home/>Home</span><span><Film/>Movies</span><span><Bookmark/>Saved</span><span><User/>Profile</span></nav>}
function HomePage({user,logout}){return <div className="home"><header><button><Menu/></button><b>MOVIE<span>HUB</span></b><button><User/></button></header><section><h1>Welcome, {user.full_name||'User'}</h1><p>You are signed in successfully.</p><button onClick={logout}>Log out</button></section><Nav/></div>};createRoot(document.getElementById('root')).render(<App/>);
